# Generated by Django 3.1.2 on 2020-10-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_customer_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.CharField(default='other', max_length=20),
        ),
    ]
